### ISSUE TITLE
ES6 Module

### ISSUE THREAD

**Issue by rafaelfaria** [dmatteo/jsdomify#4] opened 2015-08-03 06:54 UTC
Hi,

I'm trying to create a unit testing importing some ES6 modules. The only way i can import my module into the unit testing is at the top level. My module needs to have the dom created to work, and jsdomify apparently doesnt get executed before the import doesnt matter what i do. 

Is there any suggestion of what i can do?

It looks like this:

```
var jsdomify    = require('jsdomify').create();
var assert      = require("assert");

import { Countdown } from "../../src/countdown/countdown";
```

another alternative i tried was

```
var jsdomify    = require('jsdomify');
var assert      = require("assert");

import { Countdown } from "../../src/countdown/countdown";

// Operations
describe('Operations', () => {

    before(function() {
        jsdomify.create();
    });

    beforeEach(function() {
        jsdomify.clear();
    });

    after(function() {
        jsdomify.destroy();
    });
});
```

Any suggestions?

Thanks

**Comment by dmatteo** [comment] 2015-08-03 07:25
the problem is that when you're importing your component, you still don't have a DOM available because you are creating it in your `before` clause.

This should work: 

``` javascript
var jsdomify    = require('jsdomify');
jsdomify.create();

var assert      = require("assert");

import { Countdown } from "../../src/countdown/countdown";
```

**Comment by rafaelfaria** [comment] 2015-08-03 23:37
just to update this issue. @dmatteo help me with a quick fix to do 

```
var jsdomify  = require('jsdomify');
var assert = require("assert");
var Calc;

describe('Operations', () => {

    before(() => {  
      jsdomify.create();
      Calc = require("../js/src/Calc");
    })
```

That actually works. but still doesnt resolve the problem with "imports".

Thanks

**Comment by Munter** [comment] 2015-08-04 12:03
Sounds like `import` statements are resolved before anything else, which would explain why they are evaluated before jsdom has had a chance to run its course

**Comment by dmatteo** [comment] 2015-08-04 12:36
Do you see a way around this?

**Comment by Munter** [comment] 2015-08-05 10:58
I would have to read up on the spec, the transpiler implementation and possibly the loader used. Might be easier to just ask @guybedford if he already knows this :)

**Comment by guybedford** [comment] 2015-08-05 11:06
The fix looks right. Mixing ES6 modules and CommonJS isn't encouraged as code is running through two separate linking phases. But the behaviour you're getting is the best that can be defined for it.

**Comment by dmatteo** [comment] 2015-08-05 12:15
Alright, thanks @guybedford 

I'm closing the issue then

**Closed as completed by dmatteo** 2015-08-05 12:15 UTC
